version: '3'

services:
  # Docker-in-Docker (DinD) container
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client

  # Jenkins container that will use DinD
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    networks:
      - jenkins
    ports:
      - "8080:8080" 
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client:ro
      - /usr/bin/docker:/usr/bin/docker 

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  docker-certs-ca: 
  docker-certs-client:
